const fs = require('fs');
const uiPath = './src/i18n/ui.ts';
let content = fs.readFileSync(uiPath, 'utf8');

const seo = {
  "en": {
    "seo.h1": "Ultimate Pinterest Downloader for High-Quality Media",
    "seo.p1": "In today's visually-driven digital landscape, finding the perfect inspiration often starts and ends on Pinterest. However, saving those inspirations for offline use, mood boards, or personal archives requires a robust and reliable tool. That is where our advanced <strong>pinterest downloader</strong> comes into play. meadiasavee AI is meticulously engineered to provide a seamless, high-definition extraction experience for users globally. Whether you are an interior designer cataloging decor concepts, a fashion enthusiast curating styles, or a video editor seeking the highest quality clips, our platform stands as the premier destination to save Pinterest media in original quality.",
    "seo.p2": "The core philosophy behind our service is uncompromising quality combined with an effortless user interface. Traditional downloaders often compress files, serve excessive intrusive advertisements, or fail on specific formats like idea pins and carousels. Our tool circumvents these issues. By leveraging state-of-the-art backend extraction techniques, we ensure that every single download retains the creator's intended resolution and fidelity.",
    "seo.h2": "Comprehensive Video Pinterest Downloader Capabilities",
    "seo.p3": "One of the most sought-after features on our platform is our robust <strong>video pinterest downloader</strong> functionality. Videos on Pinterest range from quick DIY tutorials to stunning cinematic portfolios. Using our <strong>pinterest downloader video</strong> engine, you can effortlessly extract MP4 files directly to your local device without any quality degradation. We support up to 1080p and even 4K resolutions when available at the source. This makes us the go-to <strong>pinterest downloader hd</strong> solution for professionals who refuse to compromise on visual clarity.",
    "seo.p4": "For our international user base, we've optimized the platform to be fully responsive and accessible. Users searching for a reliable <strong>baixar video pinterest downloader</strong> or <strong>pinterest downloader vídeo</strong> will find that our tool handles varied URL structures and regional Pinterest domains seamlessly. No matter where you are located or what language your device is set to, the core extraction technology remains blazingly fast and universally compatible. Just copy the pin link, paste it into our search bar, and let our engine do the heavy lifting.",
    "seo.h3": "Why Choose Us Over Alternatives?",
    "seo.p5": "The internet is saturated with basic download tools, but very few offer a holistic suite of features. Users familiar with tools like <em>pinterest downloader pingrab</em> or <em>pinterest downloader savepin</em> often migrate to our platform because of our strict adherence to user privacy, our zero-spam policy, and our beautiful, modern interface. We don't employ deceptive download buttons or force you through endless redirect loops. Our minimalist design language (inspired by Vercel Geist) ensures that the focus remains entirely on getting your media as quickly as possible.",
    "seo.p6": "Furthermore, we offer unparalleled versatility. While many tools exclusively handle standard images or basic MP4s, our engine natively parses complex Pinterest formats. Need to download a multi-image carousel? We provide a seamless ZIP batch download option. Want to extract just the audio track from an aesthetic video? Our built-in MP3 extractor handles vocal isolation at 320kbps. This level of utility is rarely seen in a completely free tier, distinguishing us significantly from traditional <strong>pinterest downloader kostenlos</strong> services.",
    "seo.h4": "The Technical Edge: AI and Performance",
    "seo.p7": "What truly sets our <strong>pinterest downloader</strong> apart is the integration of advanced backend processing. We employ intelligent URL resolution that can parse standard pins, idea pins, and even shortened share links automatically. This means you never have to worry about formatting your link correctly; our system automatically normalizes the input, locates the highest resolution asset on Pinterest's content delivery network (CDN), and securely pipes it to your browser.",
    "seo.p8": "We also implement a strict 500 MB backend guardrail to ensure server stability, meaning the platform remains lightning fast even during peak traffic hours. For heavy users, our Pro Tier unlocks turbo speeds and ad-free batch processing, but the core functionality remains robust and highly capable for free users.",
    "seo.h5": "How to Use the Pinterest Downloader Video Tool",
    "seo.p9": "Using our platform is designed to be as intuitive as possible. Here is a quick step-by-step guide to mastering the <strong>pinterest downloader video</strong> utility:",
    "seo.s1": "Step 1:",
    "seo.s1d": "Navigate to Pinterest (either the web app or mobile application) and locate the video, image, or GIF you wish to save.",
    "seo.s2": "Step 2:",
    "seo.s2d": "Click the \"Share\" icon and select \"Copy Link\". The URL will be saved to your clipboard.",
    "seo.s3": "Step 3:",
    "seo.s3d": "Open meadiasavee AI and paste the link directly into the main input field at the top of the page.",
    "seo.s4": "Step 4:",
    "seo.s4d": "Click the download button. Our system will immediately process the request, bypassing preview thumbnails to fetch the original source file.",
    "seo.s5": "Step 5:",
    "seo.s5d": "Select your preferred format (e.g., Original JPG, 1080p MP4, or optimized WebP) and save it directly to your device.",
    "seo.h6": "A Commitment to Quality (Pinterest Downloader HD)",
    "seo.p10": "We understand that for creators, quality is non-negotiable. An image saved for a professional mood board must retain its sharpness, and a video used in a compilation must be artifact-free. As a dedicated <strong>pinterest downloader hd</strong> platform, we actively monitor Pinterest's CDN changes to ensure our extraction algorithms always fetch the maximum detail raw source. While other platforms might serve you a compressed 736px version of an image, we drill down to the original upload file whenever possible.",
    "seo.h7": "Global Reach and Accessibility",
    "seo.p11": "Our mission is to democratize access to high-quality media extraction tools worldwide. By catering to varied search intents—whether you are looking for a <strong>baixar video pinterest downloader</strong> in Brazil, a <strong>pinterest downloader kostenlos</strong> in Germany, or simply searching for a <strong>pinterest downloader vídeo</strong> on your mobile phone—we've engineered our infrastructure to serve you globally with minimal latency. We utilize edge computing and globally distributed CDNs to ensure that the user interface loads instantly, regardless of your geographic location.",
    "seo.h8": "Conclusion",
    "seo.p12": "In summary, meadiasavee AI is not just another utility; it is a comprehensive, AI-enhanced platform built for the modern creator. By combining a premium user interface with unrivaled backend extraction power, we have redefined what users should expect from a <strong>pinterest downloader</strong>. Say goodbye to spam, low-resolution files, and broken links. Experience the fastest, safest, and most reliable way to save Pinterest media today. Whether you are transitioning from alternatives like <em>pinterest downloader pingrab</em> or <em>pinterest downloader savepin</em>, or discovering us for the first time, we guarantee an exceptional, streamlined downloading experience."
  },
  "es": {
    "seo.h1": "Descargador definitivo de Pinterest para medios de alta calidad",
    "seo.p1": "En el panorama digital actual, impulsado por lo visual, encontrar la inspiración perfecta a menudo comienza y termina en Pinterest. Sin embargo, guardar esas inspiraciones requiere una herramienta sólida y confiable. Ahí es donde entra en juego nuestro avanzado <strong>descargador de pinterest</strong>. meadiasavee AI está meticulosamente diseñado para proporcionar una experiencia de extracción de alta definición.",
    "seo.p2": "La filosofía central detrás de nuestro servicio es la calidad sin compromisos combinada con una interfaz de usuario sin esfuerzo. Nuestra herramienta evita problemas como la compresión de archivos y la publicidad intrusiva mediante el aprovechamiento de técnicas de extracción backend de vanguardia.",
    "seo.h2": "Capacidades Integrales del Descargador de Video de Pinterest",
    "seo.p3": "Una de las características más buscadas en nuestra plataforma es nuestra robusta funcionalidad de <strong>descargador de video de pinterest</strong>. Puede extraer archivos MP4 directamente a su dispositivo local sin degradación de calidad.",
    "seo.p4": "Para nuestra base de usuarios internacionales, hemos optimizado la plataforma para que sea totalmente accesible. Nuestra herramienta maneja variadas estructuras de URL y dominios regionales sin problemas.",
    "seo.h3": "¿Por qué elegirnos frente a las alternativas?",
    "seo.p5": "Internet está saturado de herramientas de descarga básicas, pero muy pocas ofrecen un conjunto holístico de características. Nuestro lenguaje de diseño minimalista asegura que el enfoque se mantenga completamente en obtener sus medios.",
    "seo.p6": "Además, ofrecemos una versatilidad incomparable. Mientras que muchas herramientas manejan exclusivamente imágenes estándar, nuestro motor analiza nativamente formatos complejos de Pinterest, como carruseles o extracción de audio MP3.",
    "seo.h4": "La Ventaja Técnica: IA y Rendimiento",
    "seo.p7": "Lo que realmente distingue a nuestro <strong>descargador de pinterest</strong> es la integración de procesamiento backend avanzado que resuelve y analiza enlaces de manera automática.",
    "seo.p8": "También implementamos un límite estricto de 500 MB en el backend para garantizar la estabilidad del servidor.",
    "seo.h5": "Cómo usar la herramienta de descarga de videos de Pinterest",
    "seo.p9": "Usar nuestra plataforma está diseñado para ser lo más intuitivo posible. Aquí hay una guía rápida:",
    "seo.s1": "Paso 1:",
    "seo.s1d": "Navega a Pinterest y localiza el video, foto o GIF que deseas guardar.",
    "seo.s2": "Paso 2:",
    "seo.s2d": "Haz clic en el icono de compartir y selecciona \"Copiar Enlace\".",
    "seo.s3": "Paso 3:",
    "seo.s3d": "Abre meadiasavee AI y pega el enlace directamente en el campo de entrada principal.",
    "seo.s4": "Paso 4:",
    "seo.s4d": "Haz clic en el botón de descarga. Nuestro sistema procesará la solicitud de inmediato.",
    "seo.s5": "Paso 5:",
    "seo.s5d": "Selecciona tu formato preferido y guárdalo directamente en tu dispositivo.",
    "seo.h6": "Un Compromiso con la Calidad",
    "seo.p10": "Entendemos que para los creadores, la calidad no es negociable. Monitoreamos activamente los cambios en la CDN de Pinterest para garantizar las mejores resoluciones.",
    "seo.h7": "Alcance Global y Accesibilidad",
    "seo.p11": "Nuestra misión es democratizar el acceso a herramientas de extracción de medios de alta calidad en todo el mundo mediante CDN distribuidos globalmente.",
    "seo.h8": "Conclusión",
    "seo.p12": "En resumen, meadiasavee AI es una plataforma integral mejorada por IA. Diga adiós al spam, a los archivos de baja resolución y a los enlaces rotos. Experimente la forma más rápida y segura de guardar medios de Pinterest hoy."
  },
  "ja": {
    "seo.h1": "高品質メディアのための究極のPinterestダウンローダー",
    "seo.p1": "視覚主導のデジタルランドスケープにおいて、インスピレーションを見つけることはPinterestから始まります。私たちの高度な<strong>Pinterestダウンローダー</strong>は、グローバルユーザーにシームレスで高解像度の抽出体験を提供します。",
    "seo.p2": "私たちのサービスの基本理念は、妥協のない品質と使いやすいユーザーインターフェースです。最先端のバックエンド抽出技術により、元の解像度を維持します。",
    "seo.h2": "包括的なPinterest動画ダウンロード機能",
    "seo.p3": "当プラットフォームの最も人気のある機能の一つは、堅牢な<strong>Pinterest動画ダウンローダー</strong>です。MP4ファイルを品質の劣化なくローカルデバイスに抽出できます。",
    "seo.p4": "国際的なユーザーベースのために、プラットフォームを完全に最適化しました。当社のツールは、様々なURL構造をシームレスに処理します。",
    "seo.h3": "代替ツールよりも選ばれる理由",
    "seo.p5": "インターネットには基本的なダウンロードツールが溢れていますが、包括的な機能を提供するものはごくわずかです。スパムゼロのポリシーと美しいインターフェースが特徴です。",
    "seo.p6": "さらに、比類のない多用途性を提供します。カルーセルのダウンロードやMP3オーディオの抽出など、複雑なPinterestフォーマットをネイティブに解析します。",
    "seo.h4": "技術的優位性：AIとパフォーマンス",
    "seo.p7": "インテリジェントなURL解決により、標準ピン、アイデアピン、短縮リンクを自動的に解析します。",
    "seo.p8": "サーバーの安定性を確保するために500MBの制限を設けており、ピーク時でも非常に高速です。",
    "seo.h5": "Pinterest動画ダウンロードツールの使い方",
    "seo.p9": "プラットフォームの使用は直感的に設計されています。",
    "seo.s1": "ステップ 1:",
    "seo.s1d": "Pinterestを開き、保存したい動画、写真、GIFを見つけます。",
    "seo.s2": "ステップ 2:",
    "seo.s2d": "共有アイコンをクリックし、「リンクをコピー」を選択します。",
    "seo.s3": "ステップ 3:",
    "seo.s3d": "meadiasavee AIを開き、入力フィールドにリンクを貼り付けます。",
    "seo.s4": "ステップ 4:",
    "seo.s4d": "ダウンロードボタンをクリックします。システムが直ちに処理します。",
    "seo.s5": "ステップ 5:",
    "seo.s5d": "希望のフォーマットを選択し、デバイスに直接保存します。",
    "seo.h6": "品質へのこだわり",
    "seo.p10": "クリエイターにとって品質は譲れない要素です。常に最高解像度のオリジナルソースを取得します。",
    "seo.h7": "グローバルなリーチとアクセシビリティ",
    "seo.p11": "私たちの使命は、世界中で高品質なメディア抽出ツールへのアクセスを民主化することです。",
    "seo.h8": "結論",
    "seo.p12": "要約すると、meadiasavee AIは現代のクリエイターのために構築されたプラットフォームです。スパムや低解像度ファイルに別れを告げ、最も安全な方法を体験してください。"
  },
  "fr": {
    "seo.h1": "Téléchargeur Pinterest Ultime pour Médias de Haute Qualité",
    "seo.p1": "Dans le paysage numérique d’aujourd’hui, trouver l’inspiration commence souvent sur Pinterest. Notre <strong>téléchargeur pinterest</strong> avancé est conçu pour offrir une expérience d’extraction haute définition sans faille.",
    "seo.p2": "La philosophie de notre service est une qualité sans compromis combinée à une interface utilisateur simple. En utilisant des techniques d’extraction de pointe, nous garantissons la résolution d’origine.",
    "seo.h2": "Capacités Complètes de Téléchargement de Vidéos Pinterest",
    "seo.p3": "Notre fonctionnalité de <strong>téléchargeur de vidéo pinterest</strong> vous permet d’extraire des fichiers MP4 directement vers votre appareil sans aucune dégradation de qualité.",
    "seo.p4": "Pour nos utilisateurs internationaux, l’outil gère de manière transparente les structures d’URL variées et les domaines régionaux.",
    "seo.h3": "Pourquoi nous choisir ?",
    "seo.p5": "Notre respect strict de la vie privée, notre politique zéro spam et notre interface moderne nous distinguent des outils basiques.",
    "seo.p6": "Nous offrons une polyvalence inégalée, incluant le téléchargement de carrousels en ZIP et l’extraction audio MP3.",
    "seo.h4": "L’Avantage Technique : IA et Performances",
    "seo.p7": "Notre résolution d’URL intelligente analyse automatiquement les épingles standard, les épingles idées et les liens partagés.",
    "seo.p8": "Nous appliquons également une limite de 500 Mo pour garantir la stabilité des serveurs.",
    "seo.h5": "Comment utiliser le Téléchargeur Pinterest",
    "seo.p9": "Voici un guide rapide pour utiliser notre outil :",
    "seo.s1": "Étape 1 :",
    "seo.s1d": "Accédez à Pinterest et trouvez la vidéo, la photo ou le GIF que vous souhaitez enregistrer.",
    "seo.s2": "Étape 2 :",
    "seo.s2d": "Cliquez sur l’icône de partage et sélectionnez \"Copier le lien\".",
    "seo.s3": "Étape 3 :",
    "seo.s3d": "Ouvrez meadiasavee AI et collez le lien dans le champ de saisie.",
    "seo.s4": "Étape 4 :",
    "seo.s4d": "Cliquez sur le bouton de téléchargement. Notre système traitera la demande.",
    "seo.s5": "Étape 5 :",
    "seo.s5d": "Sélectionnez votre format préféré et enregistrez-le.",
    "seo.h6": "Un Engagement envers la Qualité",
    "seo.p10": "Nous surveillons activement le CDN de Pinterest pour nous assurer que nos algorithmes extraient toujours le fichier source original le plus détaillé.",
    "seo.h7": "Accessibilité Mondiale",
    "seo.p11": "Notre mission est de démocratiser l’accès à des outils d’extraction de haute qualité dans le monde entier.",
    "seo.h8": "Conclusion",
    "seo.p12": "En résumé, meadiasavee AI est une plateforme complète et améliorée par l’IA pour le créateur moderne. Dites adieu aux spams et aux fichiers de basse résolution."
  },
  "de": {
    "seo.h1": "Ultimativer Pinterest-Downloader für hochwertige Medien",
    "seo.p1": "In der heutigen visuellen Welt beginnt Inspiration oft auf Pinterest. Unser <strong>Pinterest Downloader</strong> wurde entwickelt, um eine reibungslose HD-Extraktion zu bieten.",
    "seo.p2": "Die Kernphilosophie unseres Dienstes ist kompromisslose Qualität kombiniert mit einer mühelosen Benutzeroberfläche.",
    "seo.h2": "Umfassende Video-Downloader-Funktionen",
    "seo.p3": "Unsere <strong>Pinterest Video Downloader</strong>-Funktion ermöglicht es Ihnen, MP4-Dateien ohne Qualitätsverlust direkt auf Ihr Gerät zu extrahieren.",
    "seo.p4": "Für unsere internationale Nutzerbasis haben wir die Plattform so optimiert, dass sie verschiedene URL-Strukturen und regionale Domains nahtlos verarbeitet.",
    "seo.h3": "Warum uns wählen?",
    "seo.p5": "Wir zeichnen uns durch strengen Datenschutz, eine Zero-Spam-Richtlinie und eine moderne Benutzeroberfläche aus.",
    "seo.p6": "Darüber hinaus bieten wir eine beispiellose Vielseitigkeit, einschließlich Carousel-ZIP-Downloads und MP3-Audioextraktion.",
    "seo.h4": "Der technische Vorteil: KI und Leistung",
    "seo.p7": "Unsere intelligente URL-Auflösung parst automatisch Standard-Pins, Idea-Pins und geteilte Links.",
    "seo.p8": "Wir implementieren eine 500-MB-Grenze, um die Serverstabilität zu gewährleisten.",
    "seo.h5": "Wie man das Tool benutzt",
    "seo.p9": "Die Nutzung unserer Plattform ist intuitiv gestaltet:",
    "seo.s1": "Schritt 1:",
    "seo.s1d": "Gehen Sie zu Pinterest und suchen Sie das Video, Foto oder GIF.",
    "seo.s2": "Schritt 2:",
    "seo.s2d": "Klicken Sie auf das Teilen-Symbol und wählen Sie \"Link kopieren\".",
    "seo.s3": "Schritt 3:",
    "seo.s3d": "Öffnen Sie meadiasavee AI und fügen Sie den Link in das Eingabefeld ein.",
    "seo.s4": "Schritt 4:",
    "seo.s4d": "Klicken Sie auf den Download-Button.",
    "seo.s5": "Schritt 5:",
    "seo.s5d": "Wählen Sie Ihr bevorzugtes Format und speichern Sie es.",
    "seo.h6": "Verpflichtung zur Qualität",
    "seo.p10": "Wir überwachen aktiv die CDNs von Pinterest, um sicherzustellen, dass Sie immer die Originaldateien mit der höchsten Auflösung erhalten.",
    "seo.h7": "Globale Erreichbarkeit",
    "seo.p11": "Unsere Mission ist es, den Zugang zu hochwertigen Medienextraktionstools weltweit zu demokratisieren.",
    "seo.h8": "Fazit",
    "seo.p12": "Zusammenfassend ist meadiasavee AI eine umfassende Plattform für moderne Schöpfer. Verabschieden Sie sich von Spam und qualitativ minderwertigen Dateien."
  },
  "pt": {
    "seo.h1": "Downloader Definitivo do Pinterest para Mídia de Alta Qualidade",
    "seo.p1": "No cenário digital de hoje, encontrar inspiração muitas vezes começa no Pinterest. Nosso avançado <strong>baixar video pinterest downloader</strong> foi projetado para fornecer uma experiência de extração em alta definição.",
    "seo.p2": "A filosofia central do nosso serviço é qualidade sem compromissos combinada com uma interface de usuário fácil. Nós garantimos a resolução original de cada download.",
    "seo.h2": "Recursos Completos de Download de Vídeo",
    "seo.p3": "Extraia arquivos MP4 diretamente para o seu dispositivo sem nenhuma perda de qualidade usando nosso motor <strong>pinterest downloader vídeo</strong>.",
    "seo.p4": "Otimizamos a plataforma para lidar perfeitamente com várias estruturas de URL e domínios regionais para nossa base de usuários internacionais.",
    "seo.h3": "Por que nos escolher?",
    "seo.p5": "Nos destacamos pela nossa política de zero spam, respeito à privacidade do usuário e interface moderna sem botões enganosos.",
    "seo.p6": "Também lidamos nativamente com formatos complexos do Pinterest, como carrosséis em lote (ZIP) e extração de áudio (MP3).",
    "seo.h4": "A Vantagem Técnica: IA e Desempenho",
    "seo.p7": "Nossa resolução de URL inteligente analisa pinos padrão e links curtos de compartilhamento automaticamente.",
    "seo.p8": "Também implementamos um limite estrito de 500 MB para garantir a estabilidade e velocidade do servidor.",
    "seo.h5": "Como Usar a Ferramenta",
    "seo.p9": "Aqui está um guia rápido passo a passo:",
    "seo.s1": "Passo 1:",
    "seo.s1d": "Navegue até o Pinterest e localize o vídeo, foto ou GIF.",
    "seo.s2": "Passo 2:",
    "seo.s2d": "Clique no ícone de compartilhar e selecione \"Copiar Link\".",
    "seo.s3": "Passo 3:",
    "seo.s3d": "Abra o meadiasavee AI e cole o link no campo principal.",
    "seo.s4": "Passo 4:",
    "seo.s4d": "Clique no botão de download. Nosso sistema processará instantaneamente.",
    "seo.s5": "Passo 5:",
    "seo.s5d": "Selecione o formato preferido e salve diretamente no seu dispositivo.",
    "seo.h6": "Compromisso com a Qualidade",
    "seo.p10": "Monitoramos ativamente a CDN do Pinterest para garantir as melhores resoluções originais.",
    "seo.h7": "Alcance Global",
    "seo.p11": "Nossa missão é democratizar o acesso a ferramentas de mídia de alta qualidade no mundo todo.",
    "seo.h8": "Conclusão",
    "seo.p12": "Em resumo, o meadiasavee AI é a plataforma definitiva para o criador moderno. Diga adeus ao spam e olá à qualidade."
  },
  "ko": {
    "seo.h1": "고품질 미디어를 위한 최고의 Pinterest 다운로더",
    "seo.p1": "오늘날의 시각 중심 디지털 환경에서 완벽한 영감을 찾는 것은 종종 Pinterest에서 시작됩니다. 당사의 고급 <strong>Pinterest 다운로더</strong>는 완벽한 고해상도 추출 경험을 제공합니다.",
    "seo.p2": "서비스의 핵심 철학은 타협 없는 품질과 사용하기 쉬운 인터페이스입니다. 최첨단 백엔드 추출 기술을 통해 원본 해상도를 보장합니다.",
    "seo.h2": "포괄적인 Pinterest 비디오 다운로드 기능",
    "seo.p3": "당사의 <strong>비디오 Pinterest 다운로더</strong> 기능을 사용하면 품질 저하 없이 로컬 기기로 MP4 파일을 직접 추출할 수 있습니다.",
    "seo.p4": "다양한 URL 구조와 지역 도메인을 완벽하게 처리하도록 국제 사용자 기반을 위해 최적화되었습니다.",
    "seo.h3": "우리를 선택해야 하는 이유",
    "seo.p5": "사용자 개인 정보 보호, 제로 스팸 정책 및 아름답고 현대적인 인터페이스에 대한 엄격한 준수가 우리를 돋보이게 합니다.",
    "seo.p6": "또한 다중 이미지 캐러셀(ZIP) 및 MP3 오디오 추출을 포함하여 비교할 수 없는 다양성을 제공합니다.",
    "seo.h4": "기술적 우위: AI 및 성능",
    "seo.p7": "당사의 지능형 URL 확인은 표준 핀, 아이디어 핀 및 공유 링크를 자동으로 구문 분석합니다.",
    "seo.p8": "또한 서버 안정성을 보장하기 위해 500MB의 백엔드 제한을 구현했습니다.",
    "seo.h5": "사용 방법",
    "seo.p9": "다음은 사용 방법에 대한 간단한 가이드입니다.",
    "seo.s1": "1단계:",
    "seo.s1d": "Pinterest로 이동하여 저장하려는 비디오, 사진 또는 GIF를 찾습니다.",
    "seo.s2": "2단계:",
    "seo.s2d": "공유 아이콘을 클릭하고 \"링크 복사\"를 선택합니다.",
    "seo.s3": "3단계:",
    "seo.s3d": "meadiasavee AI를 열고 입력 필드에 링크를 붙여넣습니다.",
    "seo.s4": "4단계:",
    "seo.s4d": "다운로드 버튼을 클릭합니다. 시스템이 즉시 처리합니다.",
    "seo.s5": "5단계:",
    "seo.s5d": "원하는 형식을 선택하고 기기에 직접 저장합니다.",
    "seo.h6": "품질에 대한 약속",
    "seo.p10": "항상 원본 최고 해상도의 파일을 추출할 수 있도록 Pinterest의 CDN 변경 사항을 적극적으로 모니터링합니다.",
    "seo.h7": "글로벌 접근성",
    "seo.p11": "우리의 사명은 전 세계적으로 고품질 미디어 추출 도구에 대한 접근을 민주화하는 것입니다.",
    "seo.h8": "결론",
    "seo.p12": "요약하자면, meadiasavee AI는 현대 크리에이터를 위한 포괄적인 플랫폼입니다. 스팸과 저해상도 파일에 작별을 고하세요."
  },
  "it": {
    "seo.h1": "Il Miglior Downloader Pinterest per File Multimediali di Alta Qualità",
    "seo.p1": "Nel panorama digitale di oggi, trovare l’ispirazione perfetta inizia su Pinterest. Il nostro <strong>downloader pinterest</strong> avanzato è progettato per offrire un’esperienza di estrazione in alta definizione.",
    "seo.p2": "La filosofia del nostro servizio è la qualità senza compromessi. Sfruttando tecniche di estrazione all’avanguardia, garantiamo la risoluzione originale.",
    "seo.h2": "Funzionalità Complete per il Download di Video",
    "seo.p3": "Il nostro <strong>downloader video pinterest</strong> ti permette di estrarre file MP4 direttamente sul tuo dispositivo senza alcuna perdita di qualità.",
    "seo.p4": "Per i nostri utenti internazionali, lo strumento gestisce perfettamente varie strutture di URL e domini regionali.",
    "seo.h3": "Perché Sceglierci?",
    "seo.p5": "Ci distinguiamo per la nostra politica zero spam, il rispetto per la privacy e un’interfaccia moderna senza pubblicità ingannevoli.",
    "seo.p6": "Offriamo anche una versatilità impareggiabile, gestendo formati complessi come caroselli (ZIP) ed estrazione audio (MP3).",
    "seo.h4": "Il Vantaggio Tecnico: AI e Prestazioni",
    "seo.p7": "La nostra risoluzione intelligente degli URL analizza automaticamente pin standard, idea pin e link abbreviati.",
    "seo.p8": "Abbiamo anche implementato un limite di 500 MB per garantire la stabilità dei server.",
    "seo.h5": "Come Usare lo Strumento",
    "seo.p9": "Ecco una guida rapida passo-passo:",
    "seo.s1": "Passo 1:",
    "seo.s1d": "Vai su Pinterest e individua il video, la foto o la GIF.",
    "seo.s2": "Passo 2:",
    "seo.s2d": "Clicca sull’icona di condivisione e seleziona \"Copia Link\".",
    "seo.s3": "Passo 3:",
    "seo.s3d": "Apri meadiasavee AI e incolla il link nel campo principale.",
    "seo.s4": "Passo 4:",
    "seo.s4d": "Clicca sul pulsante di download. Il nostro sistema elaborerà la richiesta.",
    "seo.s5": "Passo 5:",
    "seo.s5d": "Seleziona il formato preferito e salvalo sul tuo dispositivo.",
    "seo.h6": "Impegno per la Qualità",
    "seo.p10": "Monitoriamo costantemente il CDN di Pinterest per assicurarci di ottenere sempre il file originale alla massima risoluzione.",
    "seo.h7": "Accessibilità Globale",
    "seo.p11": "La nostra missione è democratizzare l’accesso a strumenti di estrazione multimediale di alta qualità in tutto il mondo.",
    "seo.h8": "Conclusione",
    "seo.p12": "In sintesi, meadiasavee AI è la piattaforma definitiva per i creatori moderni. Dì addio allo spam e ai file a bassa risoluzione."
  }
};

for (const [lang, dct] of Object.entries(seo)) {
    let entries = [];
    for (const [k, v] of Object.entries(dct)) {
        let escapedV = v.replace(/'/g, "\\'");
        entries.push(`    '${k}': '${escapedV}',`);
    }
    const entriesStr = entries.join('\\n');
    const regex = new RegExp(`(\\b${lang}: \\{[^}]*?)(\\n  \\},)`, 's');
    content = content.replace(regex, `$1\\n${entriesStr}$2`);
}

fs.writeFileSync(uiPath, content);
console.log("Successfully updated ui.ts with SEO strings.");
