const fs = require('fs');
let content = fs.readFileSync('./src/i18n/ui.ts', 'utf8');

const faq = {
  "en": {
    "faq.badge": "FAQ",
    "faq.title": "Frequently Asked Questions",
    "faq.desc": "Everything you need to know about downloading Pinterest media with meadiasavee AI.",
    "faq.q1": "Which is the best pinterest video downloader?",
    "faq.a1": "meadiasavee AI is widely considered the best Pinterest video downloader. It is fast, completely free, and extracts original 1080p MP4 videos without requiring any software installation or login.",
    "faq.q2": "How to use pinterest video downloader?",
    "faq.a2": "Using our Pinterest video downloader is simple: 1. Copy the link of the Pinterest video you want to save. 2. Paste the URL into the search box on our website. 3. Click the download button. 4. Choose your preferred video quality and save it to your device.",
    "faq.q3": "Is pinterest video downloader safe?",
    "faq.a3": "Yes, our Pinterest video downloader is 100% safe to use. We do not require you to install any software, we do not ask for your Pinterest login credentials, and all downloads are processed securely on our servers without logging your personal data.",
    "faq.q4": "Can people see what you download on Pinterest?",
    "faq.a4": "No. When you use a third-party tool like meadiasavee AI to download content from Pinterest, the original creator or other users cannot see that you have downloaded their media. Your downloads are completely private.",
    "faq.q5": "Is it safe to save pictures from Pinterest?",
    "faq.a5": "Yes, saving pictures from Pinterest for personal use is completely safe. Our platform ensures that the image files are extracted cleanly without any attached malware or hidden scripts.",
    "faq.q6": "Can someone see if I screenshot their Pinterest?",
    "faq.a6": "No, Pinterest does not notify users if you take a screenshot of their pins, boards, or profile. Unlike some other social media platforms, screenshotting on Pinterest is completely anonymous.",
    "faq.q7": "Is Pinterest free to download images?",
    "faq.a7": "Yes, Pinterest is free to use, and you can download images using our free online downloader. We provide high-resolution extraction at zero cost.",
    "faq.q8": "What is the best Pinterest downloader?",
    "faq.a8": "meadiasavee AI is the best overall Pinterest downloader because it supports videos, images, GIFs, carousels, and even audio extraction in the highest possible quality, all wrapped in a safe, modern interface.",
    "faq.q9": "What should I do if a download fails or the link is invalid?",
    "faq.a9": "If a download fails, first ensure that the Pinterest link is correct and points to a public pin (private boards are not supported). You can try copying the link again or refreshing the page. If the issue persists, the pin might have been removed by the creator.",
    "faq.q10": "Is there a daily limit on free downloads?",
    "faq.a10": "No, there is no strict daily limit on the number of files you can download on the free tier. However, we do enforce a 500 MB per-file backend limit to ensure the server remains fast for everyone. For unlimited batch processing, check out our Pro plan.",
    "faq.q11": "Does meadiasavee AI support downloading GIFs and Audio?",
    "faq.a11": "Absolutely! Our tool natively supports extracting animated GIFs and offers a built-in audio extractor that can pull high-quality 320kbps MP3 audio directly from Pinterest videos.",
    
    "su.title": "Supported Pinterest URL Formats",
    "su.desc": "All public Pinterest link structures are supported.",
    "su.1.type": "Short Pinterest Link",
    "su.1.desc": "Generated from the Pinterest mobile app 'Copy Link' button.",
    "su.2.type": "Standard Pin URL",
    "su.2.desc": "Direct desktop and mobile browser Pin URLs.",
    "su.3.type": "Regional Pinterest Domain",
    "su.3.desc": "Supports all localized Pinterest country extensions (in, co.uk, de, fr, etc.).",
    "su.4.type": "Idea & Carousel Pins",
    "su.4.desc": "Multi-image and multi-step idea pins."
  },
  "es": {
    "faq.badge": "PREGUNTAS FRECUENTES",
    "faq.title": "Preguntas Frecuentes",
    "faq.desc": "Todo lo que necesitas saber sobre la descarga de medios de Pinterest con meadiasavee AI.",
    "faq.q1": "¿Cuál es el mejor descargador de videos de Pinterest?",
    "faq.a1": "meadiasavee AI es ampliamente considerado el mejor descargador de videos de Pinterest. Es rápido, gratuito y extrae videos originales sin requerir instalación de software.",
    "faq.q2": "¿Cómo usar el descargador de videos de Pinterest?",
    "faq.a2": "Usar nuestro descargador es simple: 1. Copia el enlace del video. 2. Pega la URL en nuestro cuadro de búsqueda. 3. Haz clic en descargar. 4. Elige tu calidad y guárdalo.",
    "faq.q3": "¿Es seguro el descargador de videos de Pinterest?",
    "faq.a3": "Sí, nuestro descargador de videos de Pinterest es 100% seguro. No requerimos que instales ningún software ni que inicies sesión.",
    "faq.q4": "¿Puede la gente ver lo que descargas en Pinterest?",
    "faq.a4": "No. Tus descargas a través de meadiasavee AI son completamente privadas.",
    "faq.q5": "¿Es seguro guardar imágenes de Pinterest?",
    "faq.a5": "Sí, guardar imágenes de Pinterest para uso personal es completamente seguro.",
    "faq.q6": "¿Puede alguien ver si hago una captura de pantalla en su Pinterest?",
    "faq.a6": "No, Pinterest no notifica a los usuarios si tomas una captura de pantalla de sus pines.",
    "faq.q7": "¿Pinterest es gratis para descargar imágenes?",
    "faq.a7": "Sí, Pinterest es de uso gratuito y puedes descargar imágenes usando nuestro descargador gratuito.",
    "faq.q8": "¿Cuál es el mejor descargador de Pinterest?",
    "faq.a8": "meadiasavee AI es el mejor descargador de Pinterest porque admite videos, imágenes, GIFs y audios en la más alta calidad.",
    "faq.q9": "¿Qué debo hacer si falla una descarga o el enlace no es válido?",
    "faq.a9": "Asegúrate de que el enlace sea correcto y apunte a un pin público. Los tableros privados no son compatibles.",
    "faq.q10": "¿Hay un límite diario de descargas gratuitas?",
    "faq.a10": "No hay un límite estricto de descargas diarias gratuitas. Sin embargo, aplicamos un límite de 500 MB por archivo.",
    "faq.q11": "¿meadiasavee AI permite descargar GIFs y audios?",
    "faq.a11": "¡Absolutamente! Extraemos GIFs y ofrecemos un extractor de audio MP3 de 320kbps.",
    
    "su.title": "Formatos de URL de Pinterest Soportados",
    "su.desc": "Todas las estructuras de enlaces públicos de Pinterest son compatibles.",
    "su.1.type": "Enlace Corto de Pinterest",
    "su.1.desc": "Generado desde el botón 'Copiar Enlace' de la app móvil.",
    "su.2.type": "URL de Pin Estándar",
    "su.2.desc": "URLs directas del navegador de escritorio y móvil.",
    "su.3.type": "Dominio Regional de Pinterest",
    "su.3.desc": "Soporta todas las extensiones de países localizadas de Pinterest.",
    "su.4.type": "Pines de Idea y Carrusel",
    "su.4.desc": "Pines de ideas de varios pasos y múltiples imágenes."
  },
  "ja": {
    "faq.badge": "よくある質問",
    "faq.title": "よくあるご質問 (FAQ)",
    "faq.desc": "meadiasavee AIを使ったPinterestメディアのダウンロードについて知っておくべきことすべて。",
    "faq.q1": "最高のPinterest動画ダウンローダーはどれですか？",
    "faq.a1": "meadiasavee AIは、最高のPinterest動画ダウンローダーとして広く認識されています。高速で無料です。",
    "faq.q2": "Pinterest動画ダウンローダーの使い方は？",
    "faq.a2": "使い方は簡単です：1. 動画リンクをコピー 2. 検索ボックスにURLを貼り付け 3. ダウンロードをクリック 4. デバイスに保存",
    "faq.q3": "Pinterest動画ダウンローダーは安全ですか？",
    "faq.a3": "はい、100%安全に使用できます。ソフトウェアのインストールやログインは必要ありません。",
    "faq.q4": "Pinterestでダウンロードしたものを他の人に見られますか？",
    "faq.a4": "いいえ、メディアをダウンロードしたことを元の作成者や他のユーザーが見ることはできません。",
    "faq.q5": "Pinterestから画像を保存するのは安全ですか？",
    "faq.a5": "はい、個人的な使用目的で画像を保存することは完全に安全です。",
    "faq.q6": "スクリーンショットを撮ったことはバレますか？",
    "faq.a6": "いいえ、Pinterestはスクリーンショットを撮ったことをユーザーに通知しません。",
    "faq.q7": "Pinterestで画像をダウンロードするのは無料ですか？",
    "faq.a7": "はい、無料ダウンローダーを使用して高解像度で画像をダウンロードできます。",
    "faq.q8": "最高のPinterestダウンローダーは何ですか？",
    "faq.a8": "meadiasavee AIは最高のPinterestダウンローダーです。動画、画像、GIF、オーディオに対応しています。",
    "faq.q9": "ダウンロードが失敗した場合や無効なリンクの場合はどうすればよいですか？",
    "faq.a9": "リンクが正しいこと、および公開ピンであることを確認してください。非公開ボードはサポートされていません。",
    "faq.q10": "無料ダウンロードに1日の制限はありますか？",
    "faq.a10": "厳密な1日の制限はありませんが、1ファイルあたり500MBの制限があります。",
    "faq.q11": "GIFとオーディオのダウンロードに対応していますか？",
    "faq.a11": "はい！GIFの抽出と320kbps MP3オーディオの抽出をネイティブにサポートしています。",
    
    "su.title": "サポートされているPinterest URL形式",
    "su.desc": "すべての公開Pinterestリンク構造がサポートされています。",
    "su.1.type": "ショートPinterestリンク",
    "su.1.desc": "モバイルアプリの「リンクをコピー」ボタンから生成されたもの。",
    "su.2.type": "標準のピンURL",
    "su.2.desc": "デスクトップおよびモバイルブラウザの直接ピンURL。",
    "su.3.type": "地域のPinterestドメイン",
    "su.3.desc": "ローカライズされたすべてのPinterest国別拡張子をサポート。",
    "su.4.type": "アイデア＆カルーセルピン",
    "su.4.desc": "複数画像および複数ステップのアイデアピン。"
  },
  "fr": {
    "faq.badge": "FAQ",
    "faq.title": "Foire Aux Questions",
    "faq.desc": "Tout ce que vous devez savoir sur le téléchargement de médias Pinterest avec meadiasavee AI.",
    "faq.q1": "Quel est le meilleur téléchargeur de vidéos Pinterest ?",
    "faq.a1": "meadiasavee AI est largement considéré comme le meilleur téléchargeur. Il est rapide, gratuit et sûr.",
    "faq.q2": "Comment utiliser le téléchargeur de vidéos Pinterest ?",
    "faq.a2": "Copiez le lien de la vidéo, collez-le dans notre boîte de recherche, cliquez sur télécharger et enregistrez.",
    "faq.q3": "Le téléchargeur est-il sûr ?",
    "faq.a3": "Oui, il est 100% sûr. Aucun logiciel à installer ni d'identifiants requis.",
    "faq.q4": "Les gens peuvent-ils voir ce que vous téléchargez ?",
    "faq.a4": "Non, vos téléchargements sont complètement privés.",
    "faq.q5": "Est-il sûr d'enregistrer des images ?",
    "faq.a5": "Oui, enregistrer des images pour un usage personnel est complètement sûr.",
    "faq.q6": "Peut-on voir si je fais une capture d'écran ?",
    "faq.a6": "Non, Pinterest ne notifie pas les captures d'écran.",
    "faq.q7": "Pinterest est-il gratuit pour télécharger ?",
    "faq.a7": "Oui, vous pouvez télécharger gratuitement avec notre outil.",
    "faq.q8": "Quel est le meilleur téléchargeur ?",
    "faq.a8": "meadiasavee AI car il prend en charge les vidéos, images, GIF et l'extraction audio.",
    "faq.q9": "Que faire si un téléchargement échoue ?",
    "faq.a9": "Assurez-vous que le lien pointe vers une épingle publique. Les tableaux privés ne sont pas pris en charge.",
    "faq.q10": "Y a-t-il une limite quotidienne ?",
    "faq.a10": "Non, pas de limite stricte. Juste une limite de 500 Mo par fichier.",
    "faq.q11": "Prenez-vous en charge les GIF et l'audio ?",
    "faq.a11": "Absolument ! Nous extrayons les GIF et l'audio MP3 à 320 kbps.",
    
    "su.title": "Formats d'URL Pinterest Pris en Charge",
    "su.desc": "Toutes les structures de liens Pinterest publics sont prises en charge.",
    "su.1.type": "Lien Pinterest Court",
    "su.1.desc": "Généré depuis le bouton 'Copier le lien' de l'application mobile.",
    "su.2.type": "URL d'Épingle Standard",
    "su.2.desc": "URL directes sur navigateur de bureau et mobile.",
    "su.3.type": "Domaine Pinterest Régional",
    "su.3.desc": "Prend en charge toutes les extensions de pays Pinterest localisées.",
    "su.4.type": "Épingles Idées et Carrousels",
    "su.4.desc": "Épingles idées multi-images et multi-étapes."
  },
  "de": {
    "faq.badge": "FAQ",
    "faq.title": "Häufig gestellte Fragen",
    "faq.desc": "Alles, was Sie über das Herunterladen von Pinterest-Medien wissen müssen.",
    "faq.q1": "Welcher ist der beste Pinterest Video Downloader?",
    "faq.a1": "meadiasavee AI ist der beste Pinterest-Video-Downloader. Er ist schnell und 100% kostenlos.",
    "faq.q2": "Wie benutzt man den Pinterest Video Downloader?",
    "faq.a2": "Kopieren Sie den Videolink, fügen Sie ihn in unsere Suchleiste ein, klicken Sie auf Herunterladen und speichern Sie es.",
    "faq.q3": "Ist der Pinterest Video Downloader sicher?",
    "faq.a3": "Ja, 100% sicher. Keine Softwareinstallation oder Login erforderlich.",
    "faq.q4": "Können Leute sehen, was ich herunterlade?",
    "faq.a4": "Nein, Ihre Downloads sind absolut privat.",
    "faq.q5": "Ist es sicher, Bilder zu speichern?",
    "faq.a5": "Ja, das Speichern von Bildern für den persönlichen Gebrauch ist absolut sicher.",
    "faq.q6": "Sieht jemand, wenn ich einen Screenshot mache?",
    "faq.a6": "Nein, Pinterest benachrichtigt Nutzer nicht über Screenshots.",
    "faq.q7": "Ist das Herunterladen von Bildern kostenlos?",
    "faq.a7": "Ja, Sie können Bilder mit unserem kostenlosen Tool herunterladen.",
    "faq.q8": "Welcher ist der beste Downloader?",
    "faq.a8": "meadiasavee AI, da er Videos, Bilder, GIFs und Audio unterstützt.",
    "faq.q9": "Was tun, wenn ein Download fehlschlägt?",
    "faq.a9": "Stellen Sie sicher, dass es sich um einen öffentlichen Pin handelt. Private Pinnwände werden nicht unterstützt.",
    "faq.q10": "Gibt es ein tägliches Limit?",
    "faq.a10": "Nein, kein strenges Limit. Nur eine Grenze von 500 MB pro Datei.",
    "faq.q11": "Werden GIFs und Audio unterstützt?",
    "faq.a11": "Absolut! Wir unterstützen GIF- und MP3-Extraktion (320 kbps).",
    
    "su.title": "Unterstützte Pinterest-URL-Formate",
    "su.desc": "Alle öffentlichen Pinterest-Linkstrukturen werden unterstützt.",
    "su.1.type": "Kurzer Pinterest-Link",
    "su.1.desc": "Generiert über die Schaltfläche 'Link kopieren' der mobilen App.",
    "su.2.type": "Standard Pin URL",
    "su.2.desc": "Direkte URLs aus Desktop- und mobilen Browsern.",
    "su.3.type": "Regionale Pinterest-Domain",
    "su.3.desc": "Unterstützt alle lokalisierten Länderendungen.",
    "su.4.type": "Idea & Carousel Pins",
    "su.4.desc": "Mehrteilige Idea-Pins und Bilder-Karussells."
  },
  "pt": {
    "faq.badge": "PERGUNTAS FREQUENTES",
    "faq.title": "Perguntas Frequentes",
    "faq.desc": "Tudo o que você precisa saber sobre baixar mídia do Pinterest com meadiasavee AI.",
    "faq.q1": "Qual é o melhor baixador de vídeo do Pinterest?",
    "faq.a1": "meadiasavee AI é considerado o melhor. É rápido, gratuito e seguro.",
    "faq.q2": "Como usar o baixador de vídeo do Pinterest?",
    "faq.a2": "Copie o link do vídeo, cole na nossa caixa de pesquisa, clique em baixar e salve.",
    "faq.q3": "É seguro usar o baixador?",
    "faq.a3": "Sim, 100% seguro. Nenhum software para instalar ou login necessário.",
    "faq.q4": "As pessoas podem ver o que você baixa?",
    "faq.a4": "Não. Seus downloads através do meadiasavee AI são totalmente privados.",
    "faq.q5": "É seguro salvar fotos?",
    "faq.a5": "Sim, salvar fotos para uso pessoal é completamente seguro.",
    "faq.q6": "Alguém pode ver se eu tirar um print?",
    "faq.a6": "Não, o Pinterest não notifica capturas de tela.",
    "faq.q7": "O Pinterest é grátis para baixar imagens?",
    "faq.a7": "Sim, e você pode baixar usando nossa ferramenta online gratuita.",
    "faq.q8": "Qual é o melhor baixador?",
    "faq.a8": "meadiasavee AI, pois suporta vídeos, imagens, GIFs e extração de áudio.",
    "faq.q9": "O que fazer se o download falhar?",
    "faq.a9": "Certifique-se de que o link seja público. Pastas privadas não são suportadas.",
    "faq.q10": "Existe limite diário?",
    "faq.a10": "Não há limite estrito de arquivos. Apenas um limite de 500 MB por arquivo.",
    "faq.q11": "Suporta GIFs e Áudio?",
    "faq.a11": "Absolutamente! Extraímos GIFs e áudio MP3 de 320kbps.",
    
    "su.title": "Formatos de URL do Pinterest Suportados",
    "su.desc": "Todas as estruturas de links públicos do Pinterest são suportadas.",
    "su.1.type": "Link Curto do Pinterest",
    "su.1.desc": "Gerado pelo botão 'Copiar Link' do aplicativo móvel.",
    "su.2.type": "URL de Pin Padrão",
    "su.2.desc": "URLs diretas de navegadores de desktop e dispositivos móveis.",
    "su.3.type": "Domínio Regional do Pinterest",
    "su.3.desc": "Suporta todas as extensões de país localizadas do Pinterest.",
    "su.4.type": "Pins de Ideia e Carrossel",
    "su.4.desc": "Pins de ideias de várias imagens e várias etapas."
  },
  "ko": {
    "faq.badge": "자주 묻는 질문",
    "faq.title": "자주 묻는 질문",
    "faq.desc": "meadiasavee AI로 Pinterest 미디어를 다운로드하는 데 필요한 모든 것.",
    "faq.q1": "최고의 Pinterest 비디오 다운로더는 무엇입니까?",
    "faq.a1": "meadiasavee AI가 최고의 다운로더로 간주됩니다. 빠르고 무료이며 안전합니다.",
    "faq.q2": "Pinterest 비디오 다운로더는 어떻게 사용합니까?",
    "faq.a2": "비디오 링크를 복사하여 검색 상자에 붙여넣고 다운로드를 클릭하여 저장합니다.",
    "faq.q3": "다운로더는 안전합니까?",
    "faq.a3": "네, 100% 안전합니다. 소프트웨어 설치나 로그인이 필요하지 않습니다.",
    "faq.q4": "다른 사람들이 내가 다운로드한 것을 볼 수 있습니까?",
    "faq.a4": "아니요. 귀하의 다운로드는 완전히 비공개입니다.",
    "faq.q5": "사진을 저장해도 안전합니까?",
    "faq.a5": "네, 개인적인 용도로 사진을 저장하는 것은 완전히 안전합니다.",
    "faq.q6": "스크린샷을 찍으면 누군가 알 수 있습니까?",
    "faq.a6": "아니요, Pinterest는 스크린샷 캡처를 알리지 않습니다.",
    "faq.q7": "이미지 다운로드는 무료입니까?",
    "faq.a7": "네, 무료 온라인 도구를 사용하여 이미지를 다운로드할 수 있습니다.",
    "faq.q8": "최고의 다운로더는 무엇입니까?",
    "faq.a8": "비디오, 이미지, GIF 및 오디오를 지원하는 meadiasavee AI가 최고입니다.",
    "faq.q9": "다운로드에 실패하면 어떻게 해야 합니까?",
    "faq.a9": "공개 핀인지 확인하십시오. 비공개 보드는 지원되지 않습니다.",
    "faq.q10": "일일 제한이 있습니까?",
    "faq.a10": "엄격한 제한은 없습니다. 파일당 500MB 제한만 있습니다.",
    "faq.q11": "GIF와 오디오를 지원합니까?",
    "faq.a11": "물론입니다! GIF 및 320kbps MP3 오디오 추출을 지원합니다.",
    
    "su.title": "지원되는 Pinterest URL 형식",
    "su.desc": "모든 공개 Pinterest 링크 구조가 지원됩니다.",
    "su.1.type": "짧은 Pinterest 링크",
    "su.1.desc": "모바일 앱의 '링크 복사' 버튼에서 생성되었습니다.",
    "su.2.type": "표준 핀 URL",
    "su.2.desc": "직접 데스크톱 및 모바일 브라우저 핀 URL.",
    "su.3.type": "지역 Pinterest 도메인",
    "su.3.desc": "지역화된 모든 Pinterest 국가 확장자를 지원합니다.",
    "su.4.type": "아이디어 및 캐러셀 핀",
    "su.4.desc": "다중 이미지 및 다단계 아이디어 핀."
  },
  "it": {
    "faq.badge": "FAQ",
    "faq.title": "Domande Frequenti",
    "faq.desc": "Tutto ciò che devi sapere sul download di file multimediali Pinterest.",
    "faq.q1": "Qual è il miglior downloader video per Pinterest?",
    "faq.a1": "meadiasavee AI è considerato il migliore. È veloce, gratuito e sicuro.",
    "faq.q2": "Come usare il downloader video di Pinterest?",
    "faq.a2": "Copia il link del video, incollalo nella nostra barra di ricerca, clicca su scarica e salva.",
    "faq.q3": "È sicuro usare il downloader?",
    "faq.a3": "Sì, sicuro al 100%. Nessuna installazione o login richiesti.",
    "faq.q4": "Le persone possono vedere cosa scarico?",
    "faq.a4": "No. I tuoi download sono completamente privati.",
    "faq.q5": "È sicuro salvare foto?",
    "faq.a5": "Sì, salvare foto per uso personale è completamente sicuro.",
    "faq.q6": "Qualcuno può vedere se faccio uno screenshot?",
    "faq.a6": "No, Pinterest non notifica gli screenshot.",
    "faq.q7": "Scaricare immagini è gratuito?",
    "faq.a7": "Sì, puoi scaricare usando il nostro strumento gratuito.",
    "faq.q8": "Qual è il miglior downloader?",
    "faq.a8": "meadiasavee AI perché supporta video, immagini, GIF ed estrazione audio.",
    "faq.q9": "Cosa fare se un download fallisce?",
    "faq.a9": "Assicurati che il pin sia pubblico. Le bacheche private non sono supportate.",
    "faq.q10": "C'è un limite giornaliero?",
    "faq.a10": "Nessun limite rigido. Solo un limite di 500 MB per file.",
    "faq.q11": "Supporta GIF e audio?",
    "faq.a11": "Assolutamente! Estraiamo GIF e audio MP3 a 320kbps.",
    
    "su.title": "Formati URL Pinterest Supportati",
    "su.desc": "Tutte le strutture di link pubblici di Pinterest sono supportate.",
    "su.1.type": "Link Pinterest Breve",
    "su.1.desc": "Generato dal pulsante 'Copia Link' dell'app mobile.",
    "su.2.type": "URL Pin Standard",
    "su.2.desc": "URL diretti da browser desktop e mobile.",
    "su.3.type": "Dominio Pinterest Regionale",
    "su.3.desc": "Supporta tutte le estensioni nazionali localizzate di Pinterest.",
    "su.4.type": "Pin Idea e Carosello",
    "su.4.desc": "Pin idea multi-immagine e multi-fase."
  }
};

for (const [lang, dct] of Object.entries(faq)) {
    let entries = [];
    for (const [k, v] of Object.entries(dct)) {
        let escapedV = v.replace(/'/g, "\\'");
        entries.push(`    '${k}': '${escapedV}',`);
    }
    const entriesStr = entries.join('\\n');
    const regex = new RegExp(`(\\b${lang}: \\{[^}]*?)(\\n  \\},)`, 's');
    content = content.replace(regex, `$1\\n${entriesStr}$2`);
}

// Fix literal newlines
content = content.replace(/\\n\s+'/g, '\n    \'');

fs.writeFileSync('./src/i18n/ui.ts', content);
console.log("Successfully injected FAQ and SupportedUrls strings into ui.ts");
